# fish completion for ttysvg

complete -c ttysvg -s o -r -F -d 'Output SVG file or directory'
complete -c ttysvg -l gz -d 'Write a gzip-compressed .svgz file'
complete -c ttysvg -l size -r -d 'Recording size as COLSxROWS (either side optional: 100x, x30)'
complete -c ttysvg -l fps -r -d 'Target frames per second; sets capture rate (overrides -frame/-idle)'
complete -c ttysvg -l frame -r -d 'Minimum time between SVG frames, e.g. 80ms'
complete -c ttysvg -l idle -r -d 'Capture after output silence, e.g. 60ms (0 disables)'
complete -c ttysvg -l font-size -r -d 'SVG output font size in pixels'
complete -c ttysvg -l font-family -r -d 'SVG CSS font-family'
complete -c ttysvg -l cell-width -r -d 'SVG terminal cell width in pixels'
complete -c ttysvg -l cell-height -r -d 'SVG terminal cell height in pixels'
complete -c ttysvg -l padding -r -d 'SVG padding in pixels'
complete -c ttysvg -l theme -x -a 'auto dark light' -d 'SVG theme'
complete -c ttysvg -l bg -r -d 'Background color during recording, e.g. #0d1117'
complete -c ttysvg -l query-terminal -d 'Query/identify terminal colors, theme, and font before recording'
complete -c ttysvg -l no-clear -d 'Do not clear terminal before recording starts'
complete -c ttysvg -l autostart -d 'In pane mode, begin recording immediately instead of waiting for Ctrl-\'
complete -c ttysvg -l headless -d 'Record the requested size directly with no interactive pane; for scripting and CI'
complete -c ttysvg -l no-loop -d 'Play once and freeze the final screen instead of looping'
complete -c ttysvg -l hold -r -d 'Final-screen hold before the loop repeats, e.g. 2s'
complete -c ttysvg -l cast -r -F -d 'Convert an asciinema .cast file to SVG'
complete -c ttysvg -l version -d 'Print version and exit'
complete -c ttysvg -s q -d 'Suppress progress and summary'
complete -c ttysvg -s h -l help -d 'Show help'
complete -c ttysvg -l -- -d 'Stop option parsing'
